receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 16
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:4000
            - https://*.example.com
          allowed_headers:
            - Cors-Header
          max_age: 3600

  hostmetrics:
    collection_interval: 30s
    scrapers:
      disk:
      filesystem:
      load:
      network:

  hostmetrics/frequent:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:

  prometheus_simple:
    collection_interval: 10s
    endpoint: "host.docker.internal:8080"
    metrics_path: '/metrics'
    use_service_account: false

  filelog:
    include:
      - /var/log/*.log
    start_at: end
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'
        severity:
          parse_from: attributes.sev

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 100

  batch:
    timeout: 2s
    send_batch_size: 1024
    send_batch_max_size: 2048

  resource:
    attributes:
      - key: service.namespace
        value: node-apollo_from_config
        action: upsert
      - key: deployment.environment
        value: local_from_config
        action: upsert
      - key: service.name
        action: delete

  attributes:
    actions:
      - key: password
        action: delete
      - key: useremail
        action: hash
      - key: collector.attribute
        value: collector-value-from-config
        action: insert

  filter: #https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#converters
    error_mode: ignore
    traces:
      span:
        - 'name == "hello-span"'
      spanevent:
        - 'attributes["value"] == 0'
    metrics:
      metric:
        - 'name != "request-count"'
      datapoint:
        - 'value_double < 2'

  tail_sampling:
    decision_wait: 10s
    policies:
      - name: slow-traces
        type: latency
        latency:
          threshold_ms: 1000
      - name: probabilistic
        type: probabilistic
        probabilistic:
          sampling_percentage: 10

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://localhost:4318
    encoding: json
  googlecloud:
    project: fake-project

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, filter, tail_sampling, batch]
      exporters: [debug, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, filter, batch]
      exporters: [debug, otlphttp]
    logs:
      receivers: [filelog]
      processors: [memory_limiter, resource, attributes, filter, batch]
      exporters: [debug, otlphttp]
